behaviors:
  USVBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 1e-4
      learning_rate_schedule: linear
      beta: 0.01
      epsilon: 0.3
      lambd: 0.95

    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      activation: tanh

      encoding_size: 64
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99

    max_steps: 2000000
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: true